//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.22 at 06:34:36 PM IDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/person", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package core.person;
